author: Steve Yan # 作者
description: SteveYan's Note Blog
keyword: 
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 # Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
# donate: true

# qrcode
# qrcode: true

# comment
# you can set gitment or uyan

# comment: gitment

# gitment config
# gitment_owner: tinggengyan
# gitment_repo: tinggengyan.github.io
# gitment_oauth_id: 
# gitment_oauth_secret: 

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  avatar: /images/avatar.png
  description: "The end is always near."
  github_username: tinggengyan

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
